# NumPy Practice
The purpose of this notebook is to demonstarte my understanding of utilizing NumPy for Data Analysis. I will be able to manipulate numerical data using statistics, numPy methods, arrays, list, and dictionaries.  

**Objective:** Write a function *"that uses Numpy to output the mean, variance, standard deviation, max, min, and sum of the rows, columns, and elements in a 3 x 3 matrix."*

In [12]:
# Importing Libraries 
import pandas as pd
import numpy as np

# The Function

In [52]:
def calculate(list_of_9):
    if len(list_of_9) == 9:
        try:
# Creating the array for the 9 diigt list
            a = np.asarray(
            list_of_9).reshape(3,3)
            a_flat = a.flatten()

# Statistical calculations
            b=(np.mean(a,axis=0),np.mean(a,axis=1),np.mean(a))
            c=(np.var(a,axis=0),np.var(a,axis=1),np.var(a_flat))
            d=(np.std(a,axis=0),np.std(a,axis=1),np.std(a_flat))
            e=(np.max(a,axis=0),np.max(a,axis=1),np.max(a_flat))
            f=(np.min(a,axis=0),np.min(a,axis=1),np.min(a_flat))
            g=(np.sum(a,axis=0),np.sum(a,axis=1),np.sum(a_flat))

# Dictionary creation
            Calculated ={'mean': b,'variance': c,
                     'standard deviation': d,'max': e,
                     'min': f, 'sum':g}
#             for value in Calculated.items():
#                 value = value.tolist()
          
    
        except ValueError: print("List must contain nine numbers.")
    return Calculated
        
        

        
  
 
        
# Format of what the function should return 

#   'mean': [axis1, axis2, flattened],
#   'variance': [axis1, axis2, flattened],
#   'standard deviation': [axis1, axis2, flattened],
#   'max': [axis1, axis2, flattened],
#   'min': [axis1, axis2, flattened],
#   'sum': [axis1, axis2, flattened]
     

## Code Testing 

In [14]:
a = [1,2,3,4,5,6,7,8,9] # Creating a list of int

In [3]:
a = np.asarray(a).reshape(3,3) # Changing list to numpy array w/ 3 x 3 metrix 

In [5]:
a # Checking the work done

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Trying Out The Function 

In [53]:
calculate(a) 
# The function is working but it is returning arrays 
# We need it to return list of int not arrays 

{'mean': (array([4., 5., 6.]), array([2., 5., 8.]), 5.0),
 'variance': (array([6., 6., 6.]),
  array([0.66666667, 0.66666667, 0.66666667]),
  6.666666666666667),
 'standard deviation': (array([2.44948974, 2.44948974, 2.44948974]),
  array([0.81649658, 0.81649658, 0.81649658]),
  2.581988897471611),
 'max': (array([7, 8, 9]), array([3, 6, 9]), 9),
 'min': (array([1, 2, 3]), array([1, 4, 7]), 1),
 'sum': (array([12, 15, 18]), array([ 6, 15, 24]), 45)}

In [49]:
# Creating a second list that does not have 9 digits in it
b = [1,2,3,4,5,6,7,8,9,10]
print(len(b))

10


In [48]:
calculate(b) # The Value error is not working in the function

UnboundLocalError: local variable 'Calculated' referenced before assignment

# Lets Continue ...

In [169]:
'''This function is to take in a list of 9 digits, 
convert the list in to a 3 x 3 numpy matrix,
and return a dictionay that holds the statistical calculations 
of the 3 X 3 matrix for axis 1, axis 2 and  the matrix flattened'''


def calculate_2(list_of_9):
    if True:
        len(list_of_9) == 9
        try:

# Creation of the array from the 9 digit list
            a = np.asarray(
            list_of_9).reshape(3,3)
            a_flat = a.flatten()

#Statistical calculations & coverting numpy arrays to list 
            b= np.mean(a,axis=0).tolist(),np.mean(a,axis=1).tolist(),np.mean(a_flat).tolist()
            c= np.var(a,axis=0).tolist(),np.var(a,axis=1).tolist(),np.var(a_flat).tolist()
            d= np.std(a,axis=0).tolist(),np.std(a,axis=1).tolist(),np.std(a_flat).tolist()
            e= np.max(a,axis=0).tolist(),np.max(a,axis=1).tolist(),np.max(a_flat).tolist()
            f= np.min(a,axis=0).tolist(),np.min(a,axis=1).tolist(),np.min(a_flat).tolist()
            g= np.sum(a,axis=0).tolist(),np.sum(a,axis=1).tolist(),np.sum(a_flat).tolist()

# Creating the dictionary
            Calculated ={'mean': list(b),
                         'variance': list(c),
                         'standard deviation': list(d),
                         'max': list(e),
                         'min': list(f),
                         'sum': list(g)} 
        
        except ValueError: print("List must contain nine numbers.")
        else:
            return Calculated

In [170]:
 calculate_2(a) # Testing function

{'mean': [[4.0, 5.0, 6.0], [2.0, 5.0, 8.0], 5.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[7, 8, 9], [3, 6, 9], 9],
 'min': [[1, 2, 3], [1, 4, 7], 1],
 'sum': [[12, 15, 18], [6, 15, 24], 45]}

In [182]:
# Testing error message in function 
calculate_2(b) 
print(f'length of b: {len(b)}')

List must contain nine numbers.
length of b: 10


In [183]:
c = [2,6,2,8,4,0,1,] # Creating a list of int
print(f'length of b: {len(c)}')

length of b: 7


In [176]:
calculate_2(c) # Testing error message in function

List must contain nine numbers.


# Sucess!!!
The function is working as well as the value error message. Be sure to follow the link below to view the full description of the challenge.

**Link:** https://repl.it/repls/UnluckyVictoriousDecompiler#README.md